### ISSUE TITLE
怎么找到加载的js中的错误

### ISSUE THREAD

**Issue by zhanghuanchong** [youzan/tiny-loader.js#7]
在chrome的开发者工具中，所有加载的js的错误都显示到了tiny-loader.js里面，无法定位到真正的错误位置。有什么解决方案吗？

**Comment by pangxie1991** [comment]
不会啊，我这里试了下，通过tiny-loader加载的js，如果这个js运行时有错误，在chrome调试器里面也是报的这个js的错误，而不是从tiny-loader里报出来

能否在jsbin 或者 jsfiddle 上写个简单demo，让我调试下？
麻烦了

**Comment by zhanghuanchong** [comment]
我又试了试，可以显示错误了。多谢回复！
